import React, { useState, useEffect } from 'react';
import { 
  Shield, Activity, Bell, AlertTriangle, Radio, RefreshCw, User, Cpu
} from 'lucide-react';
import { useTraffic } from '../../context/TrafficContext';
import { useWebSocket } from '../../context/WebSocketContext';
import { useAuth } from '../../context/AuthContext';

export const Navbar = () => {
  const { kpis, alerts, refreshAll, setActiveView } = useTraffic();
  const { isConnected } = useWebSocket();
  const { user } = useAuth();
  const [timeStr, setTimeStr] = useState('');

  useEffect(() => {
    const updateTime = () => {
      const now = new Date();
      setTimeStr(now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) + ' UTC');
    };
    updateTime();
    const timer = setInterval(updateTime, 1000);
    return () => clearInterval(timer);
  }, []);

  const riskScore = kpis?.risk_score?.value ?? 14.0;
  const riskSeverity = kpis?.risk_score?.severity ?? 'LOW';

  const getRiskColor = (sev) => {
    switch (sev) {
      case 'CRITICAL': return '#ef4444';
      case 'HIGH': return '#f97316';
      case 'MEDIUM': return '#f59e0b';
      default: return '#06b6d4';
    }
  };

  return (
    <header className="soc-navbar">
      {/* Brand & Identity */}
      <div className="soc-brand">
        <div className="soc-brand-icon">
          <Shield size={18} />
        </div>
        <div className="soc-brand-title">
          SECUROX <span style={{ color: '#06b6d4', fontWeight: 400 }}>TRAFFIC</span>
        </div>
        <span className="soc-brand-subtitle">SOC COMMAND CENTER</span>
      </div>

      {/* Center status indicators */}
      <div className="soc-nav-center">
        {/* Mandated Simulation Badge (Rule 42 & 51) */}
        <div className="sim-badge" title="Telemetry generated by the SECUROX Simulation & CV Engine">
          <span className="sim-pulse-dot"></span>
          DEMO / SIMULATED DATA
        </div>

        {/* WebSocket Link Status */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '12px', color: isConnected ? '#34d399' : '#f87171' }}>
          <Radio size={14} className={isConnected ? 'pulse-icon' : ''} />
          <span>{isConnected ? 'LIVE TELEMETRY' : 'OFFLINE'}</span>
        </div>

        {/* System Risk Score Meter */}
        <div 
          style={{
            display: 'flex', 
            alignItems: 'center', 
            gap: '8px', 
            background: 'var(--bg-card)', 
            padding: '4px 12px', 
            borderRadius: '6px', 
            border: `1px solid ${getRiskColor(riskSeverity)}`
          }}
          title={kpis?.risk_score?.summary || "System Risk Score"}
        >
          <span style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 600 }}>RISK SCORE</span>
          <span style={{ fontSize: '15px', fontWeight: 700, fontFamily: 'var(--font-mono)', color: getRiskColor(riskSeverity) }}>
            {riskScore.toFixed(0)}/100
          </span>
          <span className={`badge badge-${riskSeverity.toLowerCase()}`} style={{ fontSize: '10px' }}>
            {riskSeverity}
          </span>
        </div>
      </div>

      {/* Right actions & User Profile */}
      <div className="soc-nav-actions">
        {/* Live Clock */}
        <div className="soc-live-clock">
          {timeStr}
        </div>

        {/* Refresh button */}
        <button 
          className="btn btn-outline btn-sm" 
          onClick={refreshAll} 
          title="Force refresh data"
          style={{ padding: '6px' }}
        >
          <RefreshCw size={13} />
        </button>

        {/* Alert Bell */}
        <button 
          className="btn btn-outline btn-sm" 
          onClick={() => setActiveView('alert-center')}
          style={{ position: 'relative', padding: '6px 10px' }}
          title="Open Alert Center"
        >
          <Bell size={14} />
          {alerts?.length > 0 && (
            <span style={{
              position: 'absolute',
              top: '-4px',
              right: '-4px',
              background: '#ef4444',
              color: '#fff',
              fontSize: '10px',
              fontWeight: 700,
              width: '16px',
              height: '16px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              boxShadow: '0 0 6px #ef4444'
            }}>
              {alerts.length}
            </span>
          )}
        </button>

        {/* User profile */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', paddingLeft: '8px', borderLeft: '1px solid var(--border-subtle)' }}>
          <div style={{
            width: '28px',
            height: '28px',
            borderRadius: '50%',
            background: 'var(--border-medium)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'var(--cyan-accent)'
          }}>
            <User size={14} />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-main)' }}>{user?.username || 'operator'}</span>
            <span style={{ fontSize: '10px', color: 'var(--text-dim)' }}>{user?.role || 'OPERATOR'}</span>
          </div>
        </div>
      </div>
    </header>
  );
};
